# Generated by Django 3.2.15 on 2024-03-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedata',
            name='lat',
            field=models.FloatField(blank=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='geocodedata',
            name='lon',
            field=models.FloatField(blank=True, verbose_name='долгота'),
        ),
    ]
