# Generated by Django 3.2.15 on 2024-02-02 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('phonenumber', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Максимум 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='статус')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='комментарий')),
                ('registrated_at', models.DateTimeField(auto_now_add=True, verbose_name='время регистрации')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
